### ISSUE TITLE
shit

### ISSUE THREAD

**Issue by hngocuyen** [1337-sup3r-h4x0r/QuantumObfuscator#2]
replace exec to print and see a source

**Comment by lockness-Ko** [comment]
Congrats! Please refrain from profanity. If you look at the description of the project you'll notice that this was used for a capture the flag (CTF) challenge. 

If you would like to be a script kiddie and create malware in python for malicious purposes please dunk your head in a cold bucket of ice. This should wake you up to the fact that being a script kiddie won't get you very far in life and you are much better off using your time on this earth not wasting oxygen and posting rudely on random github repos, or creating malware.

Bye

**Comment by lockness-Ko** [comment]
In nicer terms it means you've got a lot of your life ahead of you kiddo and it's best not to stuff it up by distributing malware and hacking tools. It's not cool. Have a go at scanning the python package index for malware if you want a cool project :)
